# Generated by Django 4.1.5 on 2023-05-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='Assigned_Designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Assigned_Office',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Assigned_Person',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Assigned_Range',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Current_Valuation',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Ownership',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Pool_Assigned',
            field=models.BooleanField(choices=[(False, 'Pool'), (True, 'Assigned')], null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Purchased_Price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('S', 'S'), ('U', 'U'), ('Dis', 'Dis'), ('Acc', 'Acc')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='registration_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
