# Generated by Django 4.1.5 on 2023-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Assigned_Designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Assigned_Office',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Assigned_Person',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Assigned_Range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Current_Valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Pool_Assigned',
            field=models.CharField(blank=True, choices=[('Pool', 'Pool'), ('Assigned', 'Assigned')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Purchased_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('U', 'U'), ('Dis', 'Dis'), ('Acc', 'Acc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='registration_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
